spring:
  boot:
    admin:
      notify:
        enable: true
        dingtalk:
          msgtype: markdown
          keywords: Alarm
          title: 服务告警   # msgtype: markdown 时起作用
          atMobiles: 13186111103
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=95908763459b20e24fff6c28c0bc830ac3989997f6887a2580fcdb2531b7debb
          picUrl:
          messageUrl: http://localhost:8080/applications/yun-sys
