server:
  port: 8888
spring:
  application:
    name: gb28181
  redis:
    #数据库索引
    database: 6
    host: 192.168.11.131
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    my:
      #设置 redis 数据默认过期时间，默认2小时
      expiration-time: 7200000
    stream:
      key: STREAM_MRK
      consumer-group: MRK_CONSUMER
      consumer-name: MRK
  mvc:
    async:
      request-timeout: 60000


gb28181:
  sipIp: 192.168.11.1
  sipPort: 5060
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  sipDomain: 3701020049
  sipId: 37010200492000000001
  # 默认设备认证密码，后续扩展使用设备单独密码
  sipPassword: admin123
  mediaId: mediaId001
  mediaIp: 192.168.11.1
  mediaPort: 10000
